defaults:
  - model_checkpoint
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch{epoch}_step{step}"
  mode: "max"
  save_top_k: -1
  save_last: True
  auto_insert_metric_name: False

model_summary:
  max_depth: -1
